### ISSUE TITLE
Duplicate rendering of tax and baseprice

### ISSUE THREAD

**Issue by chequille** [Magenerds/GermanLaw#21] opened 2017-11-25 23:31 UTC
Hi,
the fix you made is only working for simple products.
Am using the latest release 1.0.13 and Magento 2.2.1

It is not working for configurable products.
I get always Tax and Baseprice shown two times.

The second baseprice rendering is always taking the price from the parent product.
![grafik](https://user-images.githubusercontent.com/15807794/33235793-1dd23d08-d241-11e7-9bd6-5575c13fdb9e.png)

Any idea why?
BR
Jürgen

**Comment by hhusen** [comment] 2017-12-15 09:24
same problem for 2.1.10 (2.1.11) after update from 2.1.9

problem seems to be related to tier prices. Duplicate tax text after tier price block. same problem with baseprice, but probably out of scope of this issue.

Since 2.1.10 tier prices for configurable products seem to be rendered by javascript

example 1, variation no 55 (no tier prices): 

![55-v10](https://user-images.githubusercontent.com/1244270/34035252-c2fcfd82-e181-11e7-8e66-1167c5175379.png)

example 2: variation no. 35 (tier prices)

![35-v10](https://user-images.githubusercontent.com/1244270/34035263-cba86dcc-e181-11e7-8d5c-c7509e52a8d1.png)

tax text being rendered after tier block even if no tier price for the selected variation.

Until 2.1.9 tier prices had not been rendered on product page.

**Comment by haelbichalex** [comment] 2018-01-30 10:49
same for me with Magento 2.2.2
<img width="254" alt="bildschirmfoto 2018-01-30 um 11 43 40" src="https://user-images.githubusercontent.com/15052352/35562175-dd8ccb00-05b2-11e8-8ed5-5efbf0c801ed.png">

Since I don't need tier prices I removed it in `catalog_product_view.xml` by adding `<referenceBlock name="product.price.tier" remove="true" />`

**Comment by KlausGw** [comment] 2018-02-01 11:41
Hi,
I need tier prices, but I don't want to show double Tax Info and baseprice.
Is there a way to hide that?
Magento 2.2.2

![screenshot-2018-02-01-12-35-42](https://user-images.githubusercontent.com/15573137/35676626-bb42216c-074c-11e8-9b14-7eb8006bff53.png)

Best regards
Klaus

**Comment by TheSamsa** [comment] 2018-02-07 12:59
Should be fixed with: #24 
Displays tax text either for final price or tier price, latter if there are tier prices defined.

**Comment by hhusen** [comment] 2018-02-13 11:19
Fix #24 works for me (tax text). Thank you.

**Comment by Eugenett** [comment] 2018-04-13 13:18
Hi there! May you tell please how versions of your extentions i need to install. I need BesePrice and GermanLaw. I was tried to install Full Package and got an error after install. Version of magento 2.1.11. How versions of release i need to check? Im waiting for your feedback. Thank you!

**Comment by sydekumf** [comment] 2018-04-16 07:35
Did you install the latest release? https://github.com/Magenerds/GermanLaw/releases
They should be compatible to 2.1.x

**Comment by Eugenett** [comment] 2018-04-16 07:56
Yea, installing with GermanLaw was ok, witthout any problems. Installing with composer. But when i was tried to install BasePrice, i recieving problem like: [ReflectionException]
  Class Magento\Framework\Serialize\SerializerInterface does not exist. Latest release. Any solutions ? Thank you very much!

**Comment by Eugenett** [comment] 2018-04-16 09:56
Heh, the problem is resolved. Like release guide, the last versions 1.2.0 and 1.2.1 supported magento 2.2.x. I have a problem with the Base Price. In fronted there is nothing behind empty white page. For resolving that issue was need delete all of Base Price records from DB. And reinstall module. Ok for now. Thank you!

**Closed as completed** 2018-04-16 12:38 UTC
